### ISSUE TITLE
[Valheim] Categories Issue - Unexpected response from the server while publishing package

### ISSUE THREAD

**Issue by Digitalroot** [thunderstore-io/thunderstore-cli#85]
I get the following error when I try and publish a package. TCLI v0.2.1

```
ERROR: Unexpected response from the server while publishing package: Status code: 400 BadRequest {"categories":{"2":["Object not found"],"4":["Object not found"]}} Exiting
```

This is the content of the thunderstore.toml file. 

```bash
  icon = "./icon.png"
  outdir = "./build"
  readme = "./README.md"
  
  [[build.copy]]
  source = "./dist"
  target = ""
  
  [config]
  schemaVersion = "0.0.1"
  
  [package]
  containsNsfwContent = false
  description = "Make the Wisp do a better job."
  name = "Better_Wisps"
  namespace = "Digitalroot"
  versionNumber = "1.0.12"
  websiteUrl = "https://github.com/Digitalroot-Valheim/Digitalroot.Valheim.BetterWisps"
  
  [package.dependencies]
  ValheimModding-Jotunn = "2.11.5"
  denikson-BepInExPack_Valheim = "5.4.2105"
  
  [publish]
  categories = ["server-side", "client-side", "mistlands-update", "tweaks", "gear"]
  communities = ["valheim"]
  repository = "https://thunderstore.io/"
```

The two causing the error are "mistlands-update" and "gear". Both should be usable and are listed at https://thunderstore.io/api/experimental/community/valheim/category/ 

Removing them allowed the file to be published as expected. I am not using TCLI to build the package, I am providing TCLI a pre-built zip file.

**Comment by Windows10CE** [comment]
This should've been fixed in 0.1.4, with this PR: https://github.com/thunderstore-io/thunderstore-cli/pull/54

Are you running a version older than that?

**Comment by Digitalroot** [comment]
Silly me, I should have included the version. I am running 0.2.1.

**Comment by MythicManiac** [comment]
What catches my eye here is that it reports a failure to find the category for only some of the categories.

@Digitalroot can you check if changing the repository to `https://valheim.thunderstore.io/` has it work as expected? I think the CLI hasn't been updated yet to explicitly map the categories to the community, so it defaults to the domain-wide community instead (RoR2), in which the categories aren't found.

**Comment by Windows10CE** [comment]
As Mythic said, this is just due to the categories not existing in the default community for the given repository (Risk of Rain 2). This will be resolved in the linked PR by changing the category list to look like this (this is the new default, the old style is still accepted):
```toml
[publish]
repository = "https://thunderstore.io"
communities = [ "riskofrain2", "valheim" ]
[publish.categories]
valheim = ["tweaks"]
riskofrain2 = ["sotv"]
```

**Comment by Digitalroot** [comment]
> changing the repository to https://valheim.thunderstore.io/ has it work as expected?

Yes, this worked.
