### ISSUE TITLE
Docs Outdated

### ISSUE THREAD

**Issue by Lordfirespeed** [thunderstore-io/thunderstore-cli#94]
Hey, I made some minor changes to the docs to clear some things up about the toml schema:

https://github.com/Lordfirespeed/thunderstore-cli/wiki

View my changes commit-by-commit [here](https://github.com/Lordfirespeed/thunderstore-cli/wiki/Home/_history)

You can pull my changes locally, then update this repository:
```
git clone https://github.com/thunderstore-io/thunderstore-cli.wiki.git
cd thunderstore-cli.wiki
git remote add downstream https://github.com/Lordfirespeed/thunderstore-cli.wiki.git
git pull downstream master
git push origin master
```

**Comment by MythicManiac** [comment]
Thanks, I'll merge these once we get the next build done (after which they'll become accurate)

**Comment by MythicManiac** [comment]
This is now done, thanks for the contribution!
