### ISSUE TITLE
Release Outdated

### ISSUE THREAD

**Issue by Lordfirespeed** [thunderstore-io/thunderstore-cli#95]
Related: #94 

Just realised that the latest commit (providing support for community categories) didn't ever get a release. 

It would be great if a tag could get created for that so the release workflow gets triggered!

**Comment by MythicManiac** [comment]
I suspect the release was never created since the CI pipeline failed and nobody investigated why. If it's a simple fix I can probably push that along relatively soon

**Comment by Lordfirespeed** [comment]
You're right, it looks like the build/test task failed.

The logs aren't available, but running the action locally, it looks like it fails because it's missing the `cargo` tool.

I'll open a pull request to update the workflows.

**Comment by MythicManiac** [comment]
Huh, does the dotnet build workflow use `cargo`? Just making sure you're not looking at the rust branch

**Comment by Lordfirespeed** [comment]
The `tcli-bepinex-installer` sub-project is written in Rust, and the `ThunderstoreCLI` project is configured to build and bundle it. [Here](https://github.com/thunderstore-io/thunderstore-cli/blob/9de949ba975a55505fc4f7a81716ae9c1b75c814/ThunderstoreCLI/ThunderstoreCLI.csproj#L76C6-L76C6)

Looking at the workfllow triggers, it seems only the `test` workflow is fully automated. 

The `release` workflow runs when a new SemVer tag is pushed to the repository, and it generates a draft GitHub release which it adds build artifacts to.

The `publish` workflow runs when the drafts are published, and it grabs the `nupkg` build artifact  then pushes it to NuGet.

**Comment by MythicManiac** [comment]
@Lordfirespeed new build tagged as 0.2.2, could you check if it works as you expected?

**Comment by Lordfirespeed** [comment]
@MythicManiac Just to let you know:
```
Response status code does not indicate success: 403 (The specified API key is invalid, has expired, or does not have permission to access the specified package.).
```
^ (from NuGet in the publish workflow)

I'll test using the `.nupkg` in GitHub releases in the meantime

**Comment by MythicManiac** [comment]
That's quite the coincidence, looks like the key expired quite literally yesterday. Should be updated now

**Comment by MythicManiac** [comment]
Seems to have finished just fine now: https://github.com/thunderstore-io/thunderstore-cli/actions/runs/7118270941/job/19436983229

**Comment by Lordfirespeed** [comment]
It seems to work as intended, except all commands return exit-code 0. It looks like the 'assembly version' metadata hasn't been set in the way it wants, which is causing the update checker to throw a tantrum ...

**Comment by Lordfirespeed** [comment]
Those slimy ...! https://github.com/adamralph/minver/commit/8a852d13a9dd0f088b4c425447450b155cdd579f

**Comment by MythicManiac** [comment]
@Lordfirespeed merged #98 and released 0.2.3, let me know if that works

**Comment by Lordfirespeed** [comment]
Yep, looks good - There's one small issue, which is that the build metadata is visible to users: 
```bash
joeclack@foundation:~$ tcli 
tcli 0.2.3+10b73c843f2dd1a9ed9c6cb687dbbaa555626052
Copyright (C) 2023 Thunderstore
...
```
I'm not sure how to tell MinVer not to include it.

**Comment by MythicManiac** [comment]
I'd consider that a non-issue. Perhaps a bit noisy visually, but it's not like it's wrong.

Closing this issue now, thanks for the help 👍
